package com.zufangbao.sun.ledgerbook;

import java.io.File;
import java.util.HashMap;
import java.util.Map;

import org.apache.commons.io.FileUtils;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.TypeReference;
import com.demo2do.core.utils.JsonUtils;

public class ChartOfAccount {
	
	public static String SUFFIX_OF_INDEPENDENT_ASSETS = "_INDEPENDENT_ASSETS";
	
	public static  String FST_UNEARNED_LOAN_ASSET="FST_UNEARNED_LOAN_ASSET";
	
	public static String FST_RECIEVABLE_ASSET="FST_RECIEVABLE_ASSET";
	
	public static String FST_PAYABLE_LIABILITY="FST_PAYABLE_ASSET";
	public static String FST_LONGTERM_LIABILITY="FST_LONGTERM_LIABILITY";
	
	public static String FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS="FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS";
	
	public static String FST_BANK_SAVING="FST_BANK_SAVING";
	
	public static String FST_REVENUE="FST_REVENUE";
	public static String FST_COST="FST_COST";
	
	public static String FST_FINANCIAL_ASSETS_SOLD_FOR_REPURCHASE="FST_FINANCIAL_ASSETS_SOLD_FOR_REPURCHASE";
	public static String FST_DEFERRED_INCOME="FST_DEFERRED_INCOME";

	public static String FST_ACCOUNT_RECEIVED_IN_ADVANCE = "FST_ACCOUNT_RECEIVED_IN_ADVANCE";
	
	public static  String FST_UNEARNED_LOAN_ASSET_CODE=""+10000;
	
	public static String FST_RECIEVABLE_ASSET_CODE=""+20000;
	
	public static String FST_PAYABLE_LIABILITY_CODE=""+30000;
	public static String FST_LONGTERM_LIABILITY_CODE=""+40000;
	
	public static String FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS_CODE=""+50000;
	
	public static String FST_BANK_SAVING_CODE=""+60000;
	
	public static String FST_REVENUE_CODE=""+70000;
	
	public static String FST_FINANCIAL_ASSETS_SOLD_FOR_REPURCHASE_CODE=""+80000;
	public static String FST_COST_CODE=""+90000;
	public static String FST_DEFERRED_INCOME_CODE=""+100000;
	
	public static String FST_ACCOUNT_RECEIVED_IN_ADVANCE_CODE = ""+110000;
	
	public static  String SND_UNEARNED_LOAN_ASSET_PRINCIPLE="SND_UNEARNED_LOAN_ASSET_PRINCIPLE";
	public static  String SND_UNEARNED_LOAN_ASSET_INTEREST="SND_UNEARNED_LOAN_ASSET_INTEREST";
	public static  String SND_UNEARNED_LOAN_ASSET_LOAN_SERVICE_FEE="SND_UNEARNED_LOAN_ASSET_LOAN_SERVICE_FEE";
	public static  String SND_UNEARNED_LOAN_ASSET_TECH_FEE="SND_UNEARNED_LOAN_ASSET_TECH_FEE";
	public static  String SND_UNEARNED_LOAN_ASSET_OTHER_FEE="SND_UNEARNED_LOAN_ASSET_OTHER_FEE";
	
	
	public static String SND_REVENUE_INVESTMENT_INCOMING="SND_REVENUE_INVESTMENT_INCOMING";
	public static String SND_REVENUE_INTEREST="SND_REVENUE_INTEREST";
	public static String SND_REVENUE_INVESTMENT_ESTIMATE="SND_REVENUE_INVESTMENT_ESTIMATE";
	
	public static String SND_REVENUE_INCOME_FEE="SND_REVENUE_INCOME_FEE";
	public static String TRD_REVENUE_INCOME_LOAN_SERVICE_FEE="TRD_REVENUE_INCOME_LOAN_SERVICE_FEE";
	public static String TRD_REVENUE_INCOME_LOAN_TECH_FEE="TRD_REVENUE_INCOME_LOAN_TECH_FEE";
	public static String TRD_REVENUE_INCOME_LOAN_OTHER_FEE="TRD_REVENUE_INCOME_LOAN_OTHER_FEE";
	
	public static String SND_REVENUE_OVERDUE_FEE="SND_REVENUE_OVERDUE_FEE";
	public static String TRD_REVENUE_OVERDUE_FEE_OBLIGATION="TRD_REVENUE_OVERDUE_FEE_OBLIGATION";
	public static String TRD_REVENUE_OVERDUE_FEE_SERVICE_FEE="TRD_REVENUE_OVERDUE_FEE_SERVICE_FEE";
	public static String TRD_REVENUE_OVERDUE_FEE_OTHER_FEE="TRD_REVENUE_OVERDUE_FEE_OTHER_FEE";
	
	public static String SND_LONGTERM_LIABILITY_ABSORB_SAVING="SND_LONGTERM_LIABILITY_ABSORB_SAVING";
	
	
	public static String SND_RECIEVABLE_LOAN_ASSET="SND_RECIEVABLE_LOAN_ASSET";
	public static String SND_RECIEVABLE_OVERDUE_LOAN_ASSET="SND_RECIEVABLE_OVERDUE_LOAN_ASSET";
	
	
	public static String SND_RECIEVABLE_LOAN_GUARANTEE="SND_RECIEVABLE_LOAN_GUARANTEE";
	
	public static  String SND_RECIEVABLE_LOAN_PENALTY="SND_RECIEVABLE_LOAN_PENALTY";
	
	public static  String TRD_RECIEVABLE_LOAN_ASSET_PRINCIPLE="TRD_RECIEVABLE_LOAN_ASSET_PRINCIPLE";
	public static  String TRD_RECIEVABLE_LOAN_ASSET_INTEREST="TRD_RECIEVABLE_LOAN_ASSET_INTEREST";
	public static  String TRD_RECIEVABLE_LOAN_ASSET_LOAN_SERVICE_FEE="TRD_RECIEVABLE_LOAN_ASSET_LOAN_SERVICE_FEE";
	public static  String TRD_RECIEVABLE_LOAN_ASSET_TECH_FEE="TRD_RECIEVABLE_LOAN_ASSET_TECH_FEE";
	public static  String TRD_RECIEVABLE_LOAN_ASSET_OTHER_FEE="TRD_RECIEVABLE_LOAN_ASSET_OTHER_FEE";
	
	public static  String TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_PRINCIPLE="TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_PRINCIPLE";
	public static  String TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_INTEREST="TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_INTEREST";
	public static  String TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_LOAN_SERVICE_FEE="TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_LOAN_SERVICE_FEE";
	public static  String TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_TECH_FEE="TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_TECH_FEE";
	public static  String TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_OTHER_FEE="TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_OTHER_FEE";
	
	public static String SND_RECIEVABLE_COLLECTION="SND_RECIEVABLE_COLLECTION";
	
	public static String SND_RECIEVABLE_OVERDUE_FEE="SND_RECIEVABLE_OVERDUE_FEE";
	public static String TRD_RECIEVABLE_OVERDUE_FEE_OBLIGATION="TRD_RECIEVABLE_OVERDUE_FEE_OBLIGATION";
	public static String TRD_RECIEVABLE_OVERDUE_FEE_SERVICE_FEE="TRD_RECIEVABLE_OVERDUE_FEE_SERVICE_FEE";
	public static String TRD_RECIEVABLE_OVERDUE_FEE_OTHER_FEE="TRD_RECIEVABLE_OVERDUE_FEE_OTHER_FEE";
	
	public static  String SND_PAYABLE_CUSTODY_PRINCIPAL="SND_PAYABLE_CUSTODY_PRINCIPAL";
	public static String SND_PAYABLE_CUSTODY_LOAN_PENALTY="SND_PAYABLE_CUSTODY_LOAN_PENALTY";
	public static String SND_PAYABLE_CUSTODY_INTEREST="SND_PAYABLE_CUSTODY_INTEREST";
	public static  String SND_PAYABLE_REPURCHASE="SND_PAYABLE_REPURCHASE";
	
	public static String SND_PAYABLE_CUSTODY_SAVING="SND_OTHER_PAYABLE_CUSTODY_SAVING";
	
	public static String TRD_RECIEVABLE_COLLECTION_OVERDUE_LOAN="TRD_RECIEVABLE_COLLECTION_OVERDUE_LOAN";
	public static String TRD_RECIEVABLE_COLLECTION_OVERDUE_PENALTY="TRD_RECIEVABLE_COLLECTION_OVERDUE_PENALTY";
	
	public static String SND_LIABILITIES_INDEPENDENT_CUSTOMER_DEPOSIT="SND_LIABILITIES_INDEPENDENT_CUSTOMER_DEPOSIT";//充值
	public static String SND_LIABILITIES_INDEPENDENT_INTER_ACCOUNT_REMITTANCE="SND_LIABILITIES_INDEPENDENT_INTER_ACCOUNT_REMITTANCE";//帐内往来，支付
	public static String SND_LIABILITIES_INDEPENDENT_INTER_ACCOUNT_BENEFICIARY="SND_LIABILITIES_INDEPENDENT_INTER_ACCOUNT_BENEFICIARY";//帐内往来.首款
	public static String SND_LIABILITIES_INDEPENDENT_WITHDRAW_DEPOSIT="SND_LIABILITIES_INDEPENDENT_WITHDRAW_DEPOSIT";//提现
	
	public static String SND_DEFERRED_INCOME_INTEREST_ESTIMATE="SND_DEFERRED_INCOME_INTEREST_ESTIMATE";
	public static String SND_DEFERRED_INCOME_FEE="SND_DEFERRED_INCOME_FEE";
	
	public static String TRD_DEFERRED_INCOME_LOAN_SERVICE_FEE="TRD_DEFERRED_INCOME_LOAN_SERVICE_FEE";
	public static String TRD_DEFERRED_INCOME_LOAN_TECH_FEE="TRD_DEFERRED_INCOME_LOAN_TECH_FEE";
	public static String TRD_DEFERRED_INCOME_LOAN_OTHER_FEE="TRD_DEFERRED_INCOME_LOAN_OTHER_FEE";
	
	private static HashMap<String,TAccountInfo> entryBook=null;
	private static String entry_book_data=null;
	
	
	public static void main(String args[])
	{
		Map<String,TAccountInfo> book= EntryBook();
		String bookstr=JsonUtils.toJsonString(book);
		System.out.println(bookstr);
	}
	private static HashMap<String,TAccountInfo> read_entry_book()
	{
		String entry_book_path="src/test/resources/test/yunxin/entry_book.json";
		File entry_book_file=new File(entry_book_path);
		if(entry_book_file.exists())
		{
			try
			{
				String jsonText = FileUtils.readFileToString(entry_book_file);
			 HashMap<String,TAccountInfo> entryBook= JSON.parseObject(jsonText, new  TypeReference<HashMap<String,TAccountInfo> >(){});
			 return entryBook;
			}
			catch(Exception e)
			{
				e.printStackTrace();
				return null;
			}
			
		}
		else return null;
	}
	
    public static String SND_UNEARNED_LOAN_ASSET_INTEREST_CODE=FST_UNEARNED_LOAN_ASSET_CODE+".01";
    public static String SND_UNEARNED_LOAN_ASSET_PRINCIPLE_CODE=FST_UNEARNED_LOAN_ASSET_CODE+".02";
	public static String SND_UNEARNED_LOAN_ASSET_LOAN_SERVICE_FEE_CODE=FST_UNEARNED_LOAN_ASSET_CODE+".03";
	public static String SND_UNEARNED_LOAN_ASSET_TECH_FEE_CODE=FST_UNEARNED_LOAN_ASSET_CODE+".04";
	public static String SND_UNEARNED_LOAN_ASSET_OTHER_FEE_CODE=FST_UNEARNED_LOAN_ASSET_CODE+".05";
    
	public static String SND_RECIEVABLE_LOAN_ASSET_CODE = FST_RECIEVABLE_ASSET_CODE+".01";
	public static String SND_RECIEVABLE_LOAN_GUARANTEE_CODE = FST_RECIEVABLE_ASSET_CODE+".02";
	public static String SND_RECIEVABLE_LOAN_PENALTY_CODE = FST_RECIEVABLE_ASSET_CODE+".03";
	public static String SND_RECIEVABLE_OVERDUE_LOAN_ASSET_CODE = FST_RECIEVABLE_ASSET_CODE+".05";
	public static String SND_RECIEVABLE_OVERDUE_FEE_CODE = FST_RECIEVABLE_ASSET_CODE+".06";
	
	public static String TRD_RECIEVABLE_COLLECTION_OVERDUE_LOAN_CODE = SND_RECIEVABLE_OVERDUE_LOAN_ASSET_CODE+".01";
	public static String TRD_RECIEVABLE_COLLECTION_OVERDUE_PENALTY_CODE = SND_RECIEVABLE_OVERDUE_LOAN_ASSET_CODE+".02";
	public static  String TRD_RECIEVABLE_LOAN_ASSET_PRINCIPLE_CODE=SND_RECIEVABLE_LOAN_ASSET_CODE+".01";
	public static  String TRD_RECIEVABLE_LOAN_ASSET_INTEREST_CODE=SND_RECIEVABLE_LOAN_ASSET_CODE+".02";
	public static  String TRD_RECIEVABLE_LOAN_ASSET_LOAN_SERVICE_FEE_CODE=SND_RECIEVABLE_LOAN_ASSET_CODE+".03";
	public static  String TRD_RECIEVABLE_LOAN_ASSET_TECH_FEE_CODE=SND_RECIEVABLE_LOAN_ASSET_CODE+".04";
	public static  String TRD_RECIEVABLE_LOAN_ASSET_OTHER_FEE_CODE=SND_RECIEVABLE_LOAN_ASSET_CODE+".05";
	
	public static  String TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_PRINCIPLE_CODE=SND_RECIEVABLE_OVERDUE_LOAN_ASSET_CODE+".01";
	public static  String TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_INTEREST_CODE=SND_RECIEVABLE_OVERDUE_LOAN_ASSET_CODE+".02";
	public static  String TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_LOAN_SERVICE_FEE_CODE=SND_RECIEVABLE_OVERDUE_LOAN_ASSET_CODE+".03";
	public static  String TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_TECH_FEE_CODE=SND_RECIEVABLE_OVERDUE_LOAN_ASSET_CODE+".04";
	public static  String TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_OTHER_FEE_CODE=SND_RECIEVABLE_OVERDUE_LOAN_ASSET_CODE+".05";
	
	public static String TRD_RECIEVABLE_OVERDUE_FEE_OBLIGATION_CODE=SND_RECIEVABLE_OVERDUE_FEE_CODE+".01";
	public static String TRD_RECIEVABLE_OVERDUE_FEE_SERVICE_FEE_CODE=SND_RECIEVABLE_OVERDUE_FEE_CODE+".02";
	public static String TRD_RECIEVABLE_OVERDUE_FEE_OTHER_FEE_CODE=SND_RECIEVABLE_OVERDUE_FEE_CODE+".03";
	
	public static String SND_PAYABLE_CUSTODY_PRINCIPAL_CODE = FST_PAYABLE_LIABILITY_CODE+".01";
	public static String SND_PAYABLE_CUSTODY_LOAN_PENALTY_CODE = FST_PAYABLE_LIABILITY_CODE+".02";
	public static String SND_PAYABLE_CUSTODY_SAVING_CODE = FST_PAYABLE_LIABILITY_CODE+".03";
	public static String SND_PAYABLE_CUSTODY_INTEREST_CODE = FST_PAYABLE_LIABILITY_CODE+".04";
	public static String SND_PAYABLE_REPURCHASE_CODE = FST_PAYABLE_LIABILITY_CODE+".05";
	public static String SND_PAYABLE_COMMISSION_CODE=FST_PAYABLE_LIABILITY_CODE+".06";
	public static String SND_PAYABLE_REFUND_CODE=FST_PAYABLE_LIABILITY_CODE+".07";
	public static String SND_PAYABLE_REMITTANCE_FEE_CODE=FST_PAYABLE_LIABILITY_CODE+".08";
	
	public static String SND_PAYABLE_COMMISSION="SND_PAYABLE_COMMISSION";
	public static String SND_PAYABLE_REFUND="SND_PAYABLE_REFUND";
	public static String SND_PAYABLE_REMITTANCE_FEE="SND_PAYABLE_REMITTANCE_FEE";
	
	public static String SND_BANK_SAVING_NFQ_YL_CODE=FST_BANK_SAVING_CODE+".01";
	public static String SND_BANK_SAVING_NFQ_YL="000191400205800";//merchantId
	public static String SND_BANK_SAVING_NFQ_ZSYH_CODE=FST_BANK_SAVING_CODE+".02";
	public static String SND_BANK_SAVING_NFQ_ZSYH="955103657777777";//bankaccount、
	public static String TRD_BANK_SAVING_NFQ_ZSYH_INDEPENDENT_ASSETS=SND_BANK_SAVING_NFQ_ZSYH+SUFFIX_OF_INDEPENDENT_ASSETS;
	public static String TRD_BANK_SAVING_NFQ_ZSYH_INDEPENDENT_ASSETS_CODE=SND_BANK_SAVING_NFQ_ZSYH_CODE+".01";
	
	public static String SND_BANK_SAVING_YQB_PAYH_CODE=FST_BANK_SAVING_CODE+".03";
	public static String SND_BANK_SAVING_YQB_PAYH="19014526016005";//用钱宝bankaccount
	public static String TRD_BANK_SAVING_YQB_PAYH_INDEPENDENT_ASSETS_CODE=SND_BANK_SAVING_YQB_PAYH_CODE+".01";
	public static String TRD_BANK_SAVING_YQB_PAYH_INDEPENDENT_ASSETS=SND_BANK_SAVING_YQB_PAYH+SUFFIX_OF_INDEPENDENT_ASSETS;//用钱宝bankaccount、
	
	public static String SND_BANK_SAVING_PPD_UNION="000191400206128";//拍拍贷银联merId
	public static String SND_BANK_SAVING_PPD_UNION_CODE=FST_BANK_SAVING_CODE+".04";
	
	public static String SND_BANK_SAVING_YL_CODE=FST_BANK_SAVING_CODE+".99";
	public static String SND_BANK_SAVING_YL="001053110000001";//测试的银联merId
	
	public static String SND_COST_REMITTANCE_FEE_CODE=FST_COST_CODE+".01";
	public static String SND_COST_REFUND_CODE=FST_COST_CODE+".02";
	public static String SND_COST_COMMISSION_CODE=FST_COST_CODE+".03";
	
	public static String SND_COST_REMITTANCE_FEE="SND_COST_REMITTANCE_FEE";
	public static String SND_COST_REFUND="SND_COST_REFUND";
	public static String SND_COST_COMMISSION="SND_COST_COMMISSION";

	
	public static String SND_REVENUE_INVESTMENT_INCOMING_CODE = FST_REVENUE_CODE+".01";
	public static String SND_REVENUE_INTEREST_CODE = FST_REVENUE_CODE+".03";
	public static String SND_REVENUE_INVESTMENT_ESTIMATE_CODE=FST_REVENUE_CODE+".04";
	public static String SND_REVENUE_INCOME_FEE_CODE=FST_REVENUE_CODE+".05";
	public static String SND_REVENUE_OVERDUE_FEE_CODE=FST_REVENUE_CODE+".06";
	
	public static String SND_LIABILITIES_INDEPENDENT_CUSTOMER_DEPOSIT_CODE=FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS_CODE+".01";
	public static String SND_LIABILITIES_INDEPENDENT_INTER_ACCOUNT_REMITTANCE_CODE=FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS_CODE+".02";
	public static String SND_LIABILITIES_INDEPENDENT_INTER_ACCOUNT_BENEFICIARY_CODE=FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS_CODE+".03";
	
	public static String SND_LIABILITIES_INDEPENDENT_WITHDRAW_DEPOSIT_CODE=FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS_CODE+".04";
	
	
	public static String SND_LONGTERM_LIABILITY_ABSORB_SAVING_CODE = FST_LONGTERM_LIABILITY_CODE+".01";

	public static String SND_DEFERRED_INCOME_INTEREST_ESTIMATE_CODE = FST_DEFERRED_INCOME_CODE+".01";
	public static String SND_DEFERRED_INCOME_FEE_CODE = FST_DEFERRED_INCOME_CODE+".02";
	
	public static String TRD_DEFERRED_INCOME_LOAN_SERVICE_FEE_CODE = SND_DEFERRED_INCOME_FEE_CODE+".01";
	public static String TRD_DEFERRED_INCOME_LOAN_TECH_FEE_CODE = SND_DEFERRED_INCOME_FEE_CODE+".02";
	public static String TRD_DEFERRED_INCOME_LOAN_OTHER_FEE_CODE = SND_DEFERRED_INCOME_FEE_CODE+".03";
	
	
	public static String TRD_REVENUE_INCOME_LOAN_SERVICE_FEE_CODE = SND_REVENUE_INCOME_FEE_CODE+".01";
	public static String TRD_REVENUE_INCOME_LOAN_TECH_FEE_CODE = SND_REVENUE_INCOME_FEE_CODE+".02";
	public static String TRD_REVENUE_INCOME_LOAN_OTHER_FEE_CODE = SND_REVENUE_INCOME_FEE_CODE+".03";
	
	public static String TRD_REVENUE_OVERDUE_FEE_OBLIGATION_CODE = SND_REVENUE_OVERDUE_FEE_CODE+".01";
	public static String TRD_REVENUE_OVERDUE_FEE_SERVICE_FEE_CODE = SND_REVENUE_OVERDUE_FEE_CODE+".02";
	public static String TRD_REVENUE_OVERDUE_FEE_OTHER_FEE_CODE = SND_REVENUE_OVERDUE_FEE_CODE+".03";
	
	
	public static HashMap<String, TAccountInfo> EntryBook()
	{
		if(entryBook==null)
		{
			
		entryBook=	new HashMap<String,TAccountInfo>();
		
		
		create1stAccount(entryBook,ChartOfAccount.FST_COST,AccountSide.DEBIT,FST_COST_CODE);
		
		create1stAccount(entryBook,ChartOfAccount.FST_UNEARNED_LOAN_ASSET,AccountSide.DEBIT,FST_UNEARNED_LOAN_ASSET_CODE);
		
		create1stAccount(entryBook,ChartOfAccount.FST_RECIEVABLE_ASSET,AccountSide.DEBIT,FST_RECIEVABLE_ASSET_CODE);
		
		create1stAccount(entryBook,FST_BANK_SAVING,AccountSide.DEBIT,FST_BANK_SAVING_CODE);
		create1stAccount(entryBook,FST_PAYABLE_LIABILITY,AccountSide.CREDIT,FST_PAYABLE_LIABILITY_CODE);
		create1stAccount(entryBook,FST_LONGTERM_LIABILITY,AccountSide.CREDIT,FST_LONGTERM_LIABILITY_CODE);
		create1stAccount(entryBook,FST_REVENUE,AccountSide.CREDIT,FST_REVENUE_CODE);
		create1stAccount(entryBook,FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS,AccountSide.CREDIT,FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS_CODE);
		
		create1stAccount(entryBook,FST_FINANCIAL_ASSETS_SOLD_FOR_REPURCHASE,AccountSide.CREDIT,FST_FINANCIAL_ASSETS_SOLD_FOR_REPURCHASE_CODE);
		create1stAccount(entryBook,FST_DEFERRED_INCOME,AccountSide.CREDIT,FST_DEFERRED_INCOME_CODE);
		create1stAccount(entryBook,ChartOfAccount.FST_ACCOUNT_RECEIVED_IN_ADVANCE,AccountSide.CREDIT,FST_ACCOUNT_RECEIVED_IN_ADVANCE_CODE);
		
		
		create2NDAccount(entryBook,FST_UNEARNED_LOAN_ASSET,ChartOfAccount.SND_UNEARNED_LOAN_ASSET_PRINCIPLE,AccountSide.DEBIT,ChartOfAccount.SND_UNEARNED_LOAN_ASSET_PRINCIPLE_CODE);
		create2NDAccount(entryBook,FST_UNEARNED_LOAN_ASSET,ChartOfAccount.SND_UNEARNED_LOAN_ASSET_INTEREST,AccountSide.DEBIT,ChartOfAccount.SND_UNEARNED_LOAN_ASSET_INTEREST_CODE);
		create2NDAccount(entryBook,FST_UNEARNED_LOAN_ASSET,ChartOfAccount.SND_UNEARNED_LOAN_ASSET_LOAN_SERVICE_FEE,AccountSide.DEBIT,ChartOfAccount.SND_UNEARNED_LOAN_ASSET_LOAN_SERVICE_FEE_CODE);
		create2NDAccount(entryBook,FST_UNEARNED_LOAN_ASSET,ChartOfAccount.SND_UNEARNED_LOAN_ASSET_TECH_FEE,AccountSide.DEBIT,ChartOfAccount.SND_UNEARNED_LOAN_ASSET_TECH_FEE_CODE);
		create2NDAccount(entryBook,FST_UNEARNED_LOAN_ASSET,ChartOfAccount.SND_UNEARNED_LOAN_ASSET_OTHER_FEE,AccountSide.DEBIT,ChartOfAccount.SND_UNEARNED_LOAN_ASSET_OTHER_FEE_CODE);
		
		create2NDAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_LOAN_ASSET,AccountSide.DEBIT,SND_RECIEVABLE_LOAN_ASSET_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_LOAN_ASSET,TRD_RECIEVABLE_LOAN_ASSET_INTEREST,AccountSide.DEBIT,TRD_RECIEVABLE_LOAN_ASSET_INTEREST_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_LOAN_ASSET,TRD_RECIEVABLE_LOAN_ASSET_PRINCIPLE,AccountSide.DEBIT,TRD_RECIEVABLE_LOAN_ASSET_PRINCIPLE_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_LOAN_ASSET,TRD_RECIEVABLE_LOAN_ASSET_LOAN_SERVICE_FEE,AccountSide.DEBIT,TRD_RECIEVABLE_LOAN_ASSET_LOAN_SERVICE_FEE_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_LOAN_ASSET,TRD_RECIEVABLE_LOAN_ASSET_TECH_FEE,AccountSide.DEBIT,TRD_RECIEVABLE_LOAN_ASSET_TECH_FEE_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_LOAN_ASSET,TRD_RECIEVABLE_LOAN_ASSET_OTHER_FEE,AccountSide.DEBIT,TRD_RECIEVABLE_LOAN_ASSET_OTHER_FEE_CODE);
	
		
		create2NDAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_LOAN_GUARANTEE,AccountSide.DEBIT,SND_RECIEVABLE_LOAN_GUARANTEE_CODE);
		create2NDAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_LOAN_PENALTY,AccountSide.DEBIT,SND_RECIEVABLE_LOAN_PENALTY_CODE);
		create2NDAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_OVERDUE_LOAN_ASSET,AccountSide.DEBIT,SND_RECIEVABLE_OVERDUE_LOAN_ASSET_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_OVERDUE_LOAN_ASSET,TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_PRINCIPLE,AccountSide.DEBIT,TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_PRINCIPLE_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_OVERDUE_LOAN_ASSET,TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_INTEREST,AccountSide.DEBIT,TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_INTEREST_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_OVERDUE_LOAN_ASSET,TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_LOAN_SERVICE_FEE,AccountSide.DEBIT,TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_LOAN_SERVICE_FEE_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_OVERDUE_LOAN_ASSET,TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_TECH_FEE,AccountSide.DEBIT,TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_TECH_FEE_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_OVERDUE_LOAN_ASSET,TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_OTHER_FEE,AccountSide.DEBIT,TRD_RECIEVABLE_OVERDUE_LOAN_ASSET_OTHER_FEE_CODE);
	
		
		
		create2NDAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_OVERDUE_FEE,AccountSide.DEBIT,SND_RECIEVABLE_OVERDUE_FEE_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_OVERDUE_FEE,TRD_RECIEVABLE_OVERDUE_FEE_OBLIGATION,AccountSide.DEBIT,TRD_RECIEVABLE_OVERDUE_FEE_OBLIGATION_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_OVERDUE_FEE,TRD_RECIEVABLE_OVERDUE_FEE_SERVICE_FEE,AccountSide.DEBIT,TRD_RECIEVABLE_OVERDUE_FEE_SERVICE_FEE_CODE);
		create3rdAccount(entryBook,FST_RECIEVABLE_ASSET,SND_RECIEVABLE_OVERDUE_FEE,TRD_RECIEVABLE_OVERDUE_FEE_OTHER_FEE,AccountSide.DEBIT,TRD_RECIEVABLE_OVERDUE_FEE_OTHER_FEE_CODE);
		
		create2NDAccount(entryBook,FST_PAYABLE_LIABILITY,SND_PAYABLE_CUSTODY_LOAN_PENALTY,AccountSide.CREDIT,SND_PAYABLE_CUSTODY_LOAN_PENALTY_CODE);
		create2NDAccount(entryBook,FST_PAYABLE_LIABILITY,SND_PAYABLE_CUSTODY_SAVING,AccountSide.CREDIT,SND_PAYABLE_CUSTODY_SAVING_CODE);
		create2NDAccount(entryBook,FST_PAYABLE_LIABILITY,SND_PAYABLE_CUSTODY_INTEREST,AccountSide.CREDIT,SND_PAYABLE_CUSTODY_INTEREST_CODE);
		create2NDAccount(entryBook,FST_PAYABLE_LIABILITY,SND_PAYABLE_REPURCHASE,AccountSide.CREDIT,SND_PAYABLE_REPURCHASE_CODE);
		
		
	    create2NDAccount(entryBook,FST_LONGTERM_LIABILITY,SND_LONGTERM_LIABILITY_ABSORB_SAVING,AccountSide.CREDIT,SND_LONGTERM_LIABILITY_ABSORB_SAVING_CODE);
		create2NDAccount(entryBook,FST_REVENUE,SND_REVENUE_INVESTMENT_INCOMING,AccountSide.CREDIT,SND_REVENUE_INVESTMENT_INCOMING_CODE);
		create2NDAccount(entryBook,FST_REVENUE,SND_REVENUE_INTEREST,AccountSide.CREDIT,SND_REVENUE_INTEREST_CODE);
		create2NDAccount(entryBook,FST_REVENUE,SND_REVENUE_INVESTMENT_ESTIMATE,AccountSide.CREDIT,SND_REVENUE_INVESTMENT_ESTIMATE_CODE);
		
		
		
		create2NDAccount(entryBook,FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS,SND_LIABILITIES_INDEPENDENT_CUSTOMER_DEPOSIT,AccountSide.CREDIT,SND_LIABILITIES_INDEPENDENT_CUSTOMER_DEPOSIT_CODE);
		create2NDAccount(entryBook,FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS,SND_LIABILITIES_INDEPENDENT_INTER_ACCOUNT_REMITTANCE,AccountSide.CREDIT,SND_LIABILITIES_INDEPENDENT_INTER_ACCOUNT_REMITTANCE_CODE);
		create2NDAccount(entryBook,FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS,SND_LIABILITIES_INDEPENDENT_INTER_ACCOUNT_BENEFICIARY,AccountSide.CREDIT,SND_LIABILITIES_INDEPENDENT_INTER_ACCOUNT_BENEFICIARY_CODE);
		create2NDAccount(entryBook,FST_LIABILITIES_OF_INDEPENDENT_ACCOUNTS,SND_LIABILITIES_INDEPENDENT_WITHDRAW_DEPOSIT,AccountSide.CREDIT,SND_LIABILITIES_INDEPENDENT_WITHDRAW_DEPOSIT_CODE);
		
		create2NDAccount(entryBook,FST_DEFERRED_INCOME,SND_DEFERRED_INCOME_INTEREST_ESTIMATE,AccountSide.CREDIT,SND_DEFERRED_INCOME_INTEREST_ESTIMATE_CODE);
		
		create2NDAccount(entryBook,FST_DEFERRED_INCOME,SND_DEFERRED_INCOME_FEE,AccountSide.CREDIT,SND_DEFERRED_INCOME_FEE_CODE);
		
		
		create3rdAccount(entryBook,FST_DEFERRED_INCOME,SND_DEFERRED_INCOME_FEE,TRD_DEFERRED_INCOME_LOAN_SERVICE_FEE,AccountSide.CREDIT,TRD_DEFERRED_INCOME_LOAN_SERVICE_FEE_CODE);
		create3rdAccount(entryBook,FST_DEFERRED_INCOME,SND_DEFERRED_INCOME_FEE,TRD_DEFERRED_INCOME_LOAN_TECH_FEE,AccountSide.CREDIT,TRD_DEFERRED_INCOME_LOAN_TECH_FEE_CODE);
		create3rdAccount(entryBook,FST_DEFERRED_INCOME,SND_DEFERRED_INCOME_FEE,TRD_DEFERRED_INCOME_LOAN_OTHER_FEE,AccountSide.CREDIT,TRD_DEFERRED_INCOME_LOAN_OTHER_FEE_CODE);
		
		create2NDAccount(entryBook,FST_REVENUE,SND_REVENUE_INCOME_FEE,AccountSide.CREDIT,SND_REVENUE_INCOME_FEE_CODE);
		
		
		create3rdAccount(entryBook,FST_REVENUE,SND_REVENUE_INCOME_FEE,TRD_REVENUE_INCOME_LOAN_SERVICE_FEE,AccountSide.CREDIT,TRD_REVENUE_INCOME_LOAN_SERVICE_FEE_CODE);
		create3rdAccount(entryBook,FST_REVENUE,SND_REVENUE_INCOME_FEE,TRD_REVENUE_INCOME_LOAN_TECH_FEE,AccountSide.CREDIT,TRD_REVENUE_INCOME_LOAN_TECH_FEE_CODE);
		create3rdAccount(entryBook,FST_REVENUE,SND_REVENUE_INCOME_FEE,TRD_REVENUE_INCOME_LOAN_OTHER_FEE,AccountSide.CREDIT,TRD_REVENUE_INCOME_LOAN_OTHER_FEE_CODE);
		
		create2NDAccount(entryBook,FST_REVENUE,SND_REVENUE_OVERDUE_FEE,AccountSide.CREDIT,SND_REVENUE_OVERDUE_FEE_CODE);
		
		create3rdAccount(entryBook,FST_REVENUE,SND_REVENUE_OVERDUE_FEE,TRD_REVENUE_OVERDUE_FEE_OBLIGATION,AccountSide.CREDIT,TRD_REVENUE_OVERDUE_FEE_OBLIGATION_CODE);
		create3rdAccount(entryBook,FST_REVENUE,SND_REVENUE_OVERDUE_FEE,TRD_REVENUE_OVERDUE_FEE_SERVICE_FEE,AccountSide.CREDIT,TRD_REVENUE_OVERDUE_FEE_SERVICE_FEE_CODE);
		create3rdAccount(entryBook,FST_REVENUE,SND_REVENUE_OVERDUE_FEE,TRD_REVENUE_OVERDUE_FEE_OTHER_FEE,AccountSide.CREDIT,TRD_REVENUE_OVERDUE_FEE_OTHER_FEE_CODE);
		
		
		create2NDAccount(entryBook,FST_COST,SND_COST_REMITTANCE_FEE,AccountSide.DEBIT,SND_COST_REMITTANCE_FEE_CODE);
		create2NDAccount(entryBook,FST_COST,SND_COST_REFUND,AccountSide.DEBIT,SND_COST_REFUND_CODE);
		create2NDAccount(entryBook,FST_COST,SND_COST_COMMISSION,AccountSide.DEBIT,SND_COST_COMMISSION_CODE);
		entryBookForNFQ(entryBook);
		
		create2NDAccount(entryBook,FST_PAYABLE_LIABILITY,SND_PAYABLE_COMMISSION,AccountSide.CREDIT,SND_PAYABLE_COMMISSION_CODE);
		create2NDAccount(entryBook,FST_PAYABLE_LIABILITY,SND_PAYABLE_REFUND,AccountSide.CREDIT,SND_PAYABLE_REFUND_CODE);
		create2NDAccount(entryBook,FST_PAYABLE_LIABILITY,SND_PAYABLE_REMITTANCE_FEE,AccountSide.CREDIT,SND_PAYABLE_REMITTANCE_FEE_CODE);
		
		
		}
		
		return entryBook;
	}
	
	private static void create1stAccount(HashMap<String,TAccountInfo> entryBook,String fstAccountName,AccountSide side,String code)
	{
		Entry fstaccount=Entry.making_first_class_entry(fstAccountName,code, side);
		
		entryBook.put(fstAccountName, TAccountInfo.making_first_class_account(fstaccount));
	}
	
	public static  void create2NDAccount(HashMap<String,TAccountInfo> entryBook,String fstAccountName,String sndAccountName,AccountSide side,String code)
	{
		TAccountInfo fstaccount=entryBook.get(fstAccountName);
		
		Entry sndEntry=Entry.making_second_class_entry(sndAccountName,code, side);
		entryBook.put(sndAccountName, TAccountInfo.making_second_class_account(fstaccount.getFirstLevelAccount(),sndEntry));
		return;
	}
	public  static void create3rdAccount(HashMap<String,TAccountInfo> entryBook,String fstAccountName,String sndAccountName,String trdAccountName,AccountSide side,String code)
	{
		TAccountInfo account=entryBook.get(fstAccountName);
		Entry fstEntry=account.getFirstLevelAccount();
		account=entryBook.get(sndAccountName);
		Entry sndEntry=account.getSecondLevelAccount();
		
		Entry trdEntry=Entry.making_third_class_entry(trdAccountName, code,side);
		
		entryBook.put(trdAccountName, TAccountInfo.making_third_class_account(fstEntry,sndEntry,trdEntry));
	}
	
	public static void entryBookForNFQ(HashMap<String,TAccountInfo> entryBook)
	{
		create2NDAccount(entryBook,FST_BANK_SAVING,SND_BANK_SAVING_NFQ_YL,AccountSide.DEBIT,SND_BANK_SAVING_NFQ_YL_CODE);
		create2NDAccount(entryBook,FST_BANK_SAVING,SND_BANK_SAVING_NFQ_ZSYH,AccountSide.DEBIT,SND_BANK_SAVING_NFQ_ZSYH_CODE);
		create3rdAccount(entryBook,FST_BANK_SAVING,SND_BANK_SAVING_NFQ_ZSYH,TRD_BANK_SAVING_NFQ_ZSYH_INDEPENDENT_ASSETS,AccountSide.DEBIT,TRD_BANK_SAVING_NFQ_ZSYH_INDEPENDENT_ASSETS_CODE);

		create2NDAccount(entryBook,FST_BANK_SAVING,SND_BANK_SAVING_YQB_PAYH,AccountSide.DEBIT,SND_BANK_SAVING_YQB_PAYH_CODE);
		create3rdAccount(entryBook,FST_BANK_SAVING,SND_BANK_SAVING_YQB_PAYH,TRD_BANK_SAVING_YQB_PAYH_INDEPENDENT_ASSETS,AccountSide.DEBIT,TRD_BANK_SAVING_YQB_PAYH_INDEPENDENT_ASSETS_CODE);
		
		create2NDAccount(entryBook,FST_BANK_SAVING,SND_BANK_SAVING_PPD_UNION,AccountSide.DEBIT,SND_BANK_SAVING_PPD_UNION_CODE);
		
		
		create2NDAccount(entryBook,FST_BANK_SAVING,SND_BANK_SAVING_YL,AccountSide.DEBIT,SND_BANK_SAVING_YL_CODE);
	}
	
}
