/**
 * 
 */
package com.suidifu.coffer;

/**
 * @author zjm
 */
public class Constant {

	/**
	 * 广银联-批量代收报文模版
	 * 依次入参 ：用户名，用户密码，交易流水号，业务代码，商户号，总记录数，总金额，批扣明细列表
	 */
	public static final String GZ_UNIONPAY_BATCH_DEBIT_PACKET = "<?xml version=\"1.0\" encoding=\"gbk\"?><GZELINK><INFO><TRX_CODE>100001</TRX_CODE><VERSION>05</VERSION><DATA_TYPE>2</DATA_TYPE><LEVEL>5</LEVEL><USER_NAME>%s</USER_NAME><USER_PASS>%s</USER_PASS><REQ_SN>%s</REQ_SN><SIGNED_MSG></SIGNED_MSG></INFO><BODY><TRANS_SUM><BUSINESS_CODE>%s</BUSINESS_CODE><MERCHANT_ID>%s</MERCHANT_ID><TOTAL_ITEM>%s</TOTAL_ITEM><TOTAL_SUM>%s</TOTAL_SUM></TRANS_SUM><TRANS_DETAILS>%s</TRANS_DETAILS></BODY></GZELINK>";
	
	/**
	 * 广银联-代收数据包传递明细模版
	 * 依次入参数 ：序列号，银行代码，银行卡号，持卡人姓名，身份证号，开户行所在省，开户行所在市，金额，备注
	 */
	public static final String GZ_UNIONPAY_DEBIT_PACKET_TRANS_DETAIL = "<TRANS_DETAIL><SN>%s</SN><BANK_CODE>%s</BANK_CODE><ACCOUNT_TYPE>00</ACCOUNT_TYPE><ACCOUNT_NO>%s</ACCOUNT_NO><ACCOUNT_NAME>%s</ACCOUNT_NAME><ID>%s</ID><PROVINCE>%s</PROVINCE><CITY>%s</CITY><AMOUNT>%s</AMOUNT><REMARK>%s</REMARK></TRANS_DETAIL>";
	
	/**
	 * 广银联-实时代收报文模版
	 * 依次入参 ：用户名，用户密码，交易流水号，业务代码，商户号，总金额，实时代收明细
	 */
	public static final String GZ_UNIONPAY_REAL_TIME_DEBIT_PACKET = "<?xml version=\"1.0\" encoding=\"gbk\"?><GZELINK><INFO><TRX_CODE>100004</TRX_CODE><VERSION>05</VERSION><DATA_TYPE>2</DATA_TYPE><LEVEL>0</LEVEL><USER_NAME>%s</USER_NAME><USER_PASS>%s</USER_PASS><REQ_SN>%s</REQ_SN><SIGNED_MSG></SIGNED_MSG></INFO><BODY><TRANS_SUM><BUSINESS_CODE>%s</BUSINESS_CODE><MERCHANT_ID>%s</MERCHANT_ID><TOTAL_ITEM>1</TOTAL_ITEM><TOTAL_SUM>%s</TOTAL_SUM></TRANS_SUM><TRANS_DETAILS>%s</TRANS_DETAILS></BODY></GZELINK>";
	
	/**
	 * 广银联-交易结果查询报文模版
	 * 依次入参 ：用户名，用户密码，交易流水号，要查询对交易流水号
	 */
	public static final String GZ_UNIONPAY_BATCH_QUERY_PACKET = "<?xml version=\"1.0\" encoding=\"gbk\"?><GZELINK><INFO><TRX_CODE>200001</TRX_CODE><VERSION>05</VERSION><DATA_TYPE>2</DATA_TYPE><USER_NAME>%s</USER_NAME><USER_PASS>%s</USER_PASS><REQ_SN>%s</REQ_SN><SIGNED_MSG></SIGNED_MSG></INFO><BODY><QUERY_TRANS><QUERY_SN>%s</QUERY_SN></QUERY_TRANS></BODY></GZELINK>";
	
	public static final String GZ_UNIONPAY_DEFAULT_TRANSACTION_DETAIL_QUERY_PAGE_SIZE = "5000";
	
	/**
	 * 当日或历史查询报文模版
	 * 依次入参 ：用户名，用户密码，交易流水号，商户号，开始时间，结束时间，页码，每页记录数
	 */
	public static final String GZ_UNIONPAY_TRANSACTION_DETAIL_QUERY_PACKET = "<?xml version=\"1.0\" encoding=\"gbk\"?><GZELINK><INFO><TRX_CODE>200002</TRX_CODE><VERSION>05</VERSION><DATA_TYPE>2</DATA_TYPE><USER_NAME>%s</USER_NAME><USER_PASS>%s</USER_PASS><REQ_SN>%s</REQ_SN><SIGNED_MSG></SIGNED_MSG></INFO><BODY><QUERY_TRANS><MERCHANT_ID>%s</MERCHANT_ID><BEGIN_DATE>%s</BEGIN_DATE><END_DATE>%s</END_DATE><PAGE_NUM>%s</PAGE_NUM><PAGE_SIZE>%s</PAGE_SIZE><SF_TYPE>S</SF_TYPE><REQ_TYPE>0</REQ_TYPE><RESULT_TYPE>2</RESULT_TYPE></QUERY_TRANS></BODY></GZELINK>";
	
	public static final String GZ_UNIONPAY_ACCOUNT_DETAIL_QUERY_PACKET= "<?xml version=\"1.0\" encoding=\"gbk\"?><GZELINK><INFO><TRX_CODE>500002</TRX_CODE><VERSION>05</VERSION><DATA_TYPE>2</DATA_TYPE><USER_NAME>%s</USER_NAME><USER_PASS>%s</USER_PASS><REQ_SN>%s</REQ_SN><SIGNED_MSG></SIGNED_MSG></INFO><BODY><QUERY_TRANS><ACCOUNT_TYPE>%s</ACCOUNT_TYPE><MERCHANT_ID>%s</MERCHANT_ID><BEGIN_DATE>%s</BEGIN_DATE><END_DATE>%s</END_DATE><PAGE_NUM>%s</PAGE_NUM><PAGE_SIZE>%s</PAGE_SIZE><SF_TYPE>S</SF_TYPE><REQ_TYPE>0</REQ_TYPE><RESULT_TYPE>2</RESULT_TYPE></QUERY_TRANS></BODY></GZELINK>";
	
	/**
	 * 实时代付数据包传递明细模版
	 * 依次入参数 ：序列号，银行代码，银行卡号，持卡人姓名，开户证件类型，证件号，开户行所在省，开户行所在市，金额，备注
	 */
	public static final String PAYMENT_PACKET_TRANS_DETAIL = "<TRANS_DETAIL><SN>%s</SN><BANK_CODE>%s</BANK_CODE><ACCOUNT_TYPE>00</ACCOUNT_TYPE><ACCOUNT_NO>%s</ACCOUNT_NO><ACCOUNT_NAME>%s</ACCOUNT_NAME><ID_TYPE>0</ID_TYPE><ID>%s</ID><PROVINCE>%s</PROVINCE><CITY>%s</CITY><AMOUNT>%s</AMOUNT><REMARK>%s</REMARK></TRANS_DETAIL>";
	
	/**
	 * 实时代付模版
	 * 依次入参 ：用户名，用户密码，交易流水号，业务代码，商户号，总记录数，总金额，实时代收明细
	 */
	public static final String REAL_TIME_PAYMENT_PACKET = "<?xml version=\"1.0\" encoding=\"gbk\"?><GZELINK><INFO><TRX_CODE>100005</TRX_CODE><VERSION>05</VERSION><DATA_TYPE>2</DATA_TYPE><LEVEL>5</LEVEL><USER_NAME>%s</USER_NAME><USER_PASS>%s</USER_PASS><REQ_SN>%s</REQ_SN><SIGNED_MSG></SIGNED_MSG></INFO><BODY><TRANS_SUM><BUSINESS_CODE>%s</BUSINESS_CODE><MERCHANT_ID>%s</MERCHANT_ID><TOTAL_ITEM>%s</TOTAL_ITEM><TOTAL_SUM>%s</TOTAL_SUM></TRANS_SUM><TRANS_DETAILS>%s</TRANS_DETAILS></BODY></GZELINK>";
	
}